url: https:/cheetah.github.io
baseurl:

# Site settings
title: KOOSHA CNC
title-fa: دانلود منیجر چیتا
logo: logo.png
email: persepolis@beeit.ir
description: "Koosha CNC"
description-fa: "خدمات CNC کوشا"

# Team names, titles and social links
team:
- name: Ebrahim GHyasvand
  name-fa: سعید کیوان فر
  pic: https://avatars0.githubusercontent.com/u/6297600
  position-fa: برنامه‌نویس
  position: Programmer
  description: سابقه همکاری در شرکت های مختلف
  social:
  - title: github
    url: https:google.com

# Social networks
social:
- title: github
  url: https://github.com/skayvanfar/cheetah
